const priceData = [
    {
        title: "Massage (1h 30min) ",
        item1: "couple massage",
        item1price: "$120",
        item2: "Hot Stone",
        item2price: "$75",
        item3: "Bamboo Massage",
        item3price: "$70",
        item4: "",
        item4price: "",
        item5: "",
        item5price: "",
    },
    {
        title: "Facial & Makeup",
        item1: "Eve Taylor Skin Specific(60min)",
        item1price: "$30",
        item2: "Serene Signature Diamond Bright(75min)",
        item2price: "$50",
        item3: "Full face Makeup",
        item3price: "$30",
        item4: "Eyes Only Makeup",
        item4price: "$15",
        item5: "",
        item5price: "",
    },
    {
        title: "Waxing and Shaving",
        item1: "Eyebrow Wax",
        item1price: "$6",
        item2: "Half Leg",
        item2price: "$15",
        item3: "Full Leg",
        item3price: "$25",
        item4: "Underarm",
        item4price: "$10",
        item5: "Full Body Shaving",
        item5price: "$40",
    },
]

export default priceData